apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: petclinicdevacr.azurecr.io/spring-petclinic-config-server
          ports:
            - containerPort: 8888
          env:
            - name: NEW_RELIC_APP_NAME
              value: petclinic-config-server
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: newrelic-license
                  key: NEW_RELIC_LICENSE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: petclinic
spec:
  selector:
    app: config-server
  ports:
    - port: 8888
      targetPort: 8888
